name: CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: .
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Installation ⏳
      run: npm install
      working-directory: ${{env.working-directory}}
   
    - name: Build 🧱
      run: npm run build
      working-directory: ${{env.working-directory}}